/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "../../../../core";
import * as AccelBooks from "../../../index";
import * as serializers from "../../../../serialization/index";
import urlJoin from "url-join";
import * as errors from "../../../../errors/index";

export declare namespace Company {
    interface Options {
        environment: core.Supplier<string>;
        fetcher?: core.FetchFunction;
    }

    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
    }
}

export class Company {
    constructor(protected readonly _options: Company.Options) {}

    /**
     * Creates a new company.
     *
     * @param {AccelBooks.PostCompanyRequest} request
     * @param {Company.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AccelBooks.InternalServerError}
     *
     * @example
     *     await client.company.createCompany()
     */
    public async createCompany(
        request: AccelBooks.PostCompanyRequest = {},
        requestOptions?: Company.RequestOptions
    ): Promise<Record<string, unknown>> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(await core.Supplier.get(this._options.environment), "company"),
            method: "POST",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "accelbooks",
                "X-Fern-SDK-Version": "0.0.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.PostCompanyRequest.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return serializers.company.createCompany.Response.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 500:
                    throw new AccelBooks.InternalServerError(_response.error.body);
                default:
                    throw new errors.AccelBooksError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AccelBooksError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.AccelBooksTimeoutError();
            case "unknown":
                throw new errors.AccelBooksError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Retrieves a company by ID.
     *
     * @param {string} id - The ID of the company to retrieve.
     * @param {Company.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AccelBooks.NotFoundError}
     * @throws {@link AccelBooks.InternalServerError}
     *
     * @example
     *     await client.company.getCompany("id")
     */
    public async getCompany(id: string, requestOptions?: Company.RequestOptions): Promise<Record<string, unknown>> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(await core.Supplier.get(this._options.environment), `company/${encodeURIComponent(id)}`),
            method: "GET",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "accelbooks",
                "X-Fern-SDK-Version": "0.0.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return serializers.company.getCompany.Response.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new AccelBooks.NotFoundError(
                        serializers.NotFoundError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        })
                    );
                case 500:
                    throw new AccelBooks.InternalServerError(_response.error.body);
                default:
                    throw new errors.AccelBooksError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AccelBooksError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.AccelBooksTimeoutError();
            case "unknown":
                throw new errors.AccelBooksError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Updates a company by ID.
     *
     * @param {string} id - The ID of the company to update.
     * @param {AccelBooks.PutCompanyIdRequest} request
     * @param {Company.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AccelBooks.InternalServerError}
     *
     * @example
     *     await client.company.updateCompany("id")
     */
    public async updateCompany(
        id: string,
        request: AccelBooks.PutCompanyIdRequest = {},
        requestOptions?: Company.RequestOptions
    ): Promise<Record<string, unknown>> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(await core.Supplier.get(this._options.environment), `company/${encodeURIComponent(id)}`),
            method: "PUT",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "accelbooks",
                "X-Fern-SDK-Version": "0.0.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.PutCompanyIdRequest.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return serializers.company.updateCompany.Response.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 500:
                    throw new AccelBooks.InternalServerError(_response.error.body);
                default:
                    throw new errors.AccelBooksError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AccelBooksError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.AccelBooksTimeoutError();
            case "unknown":
                throw new errors.AccelBooksError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Deletes a company by ID.
     *
     * @param {string} id - The ID of the company to delete.
     * @param {Company.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AccelBooks.InternalServerError}
     *
     * @example
     *     await client.company.deleteCompany("id")
     */
    public async deleteCompany(id: string, requestOptions?: Company.RequestOptions): Promise<void> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(await core.Supplier.get(this._options.environment), `company/${encodeURIComponent(id)}`),
            method: "DELETE",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "accelbooks",
                "X-Fern-SDK-Version": "0.0.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return;
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 500:
                    throw new AccelBooks.InternalServerError(_response.error.body);
                default:
                    throw new errors.AccelBooksError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AccelBooksError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.AccelBooksTimeoutError();
            case "unknown":
                throw new errors.AccelBooksError({
                    message: _response.error.errorMessage,
                });
        }
    }
}
