/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as core from "../../core";

export const NotFoundError: core.serialization.Schema<
    serializers.NotFoundError.Raw,
    Record<string, unknown>
> = core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace NotFoundError {
    type Raw = Record<string, unknown>;
}
