/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as AccelBooks from "../../../../../api/index";
import * as core from "../../../../../core";

export const PutCompanyIdCategoryRequest: core.serialization.Schema<
    serializers.PutCompanyIdCategoryRequest.Raw,
    AccelBooks.PutCompanyIdCategoryRequest
> = core.serialization.object({
    name: core.serialization.string().optional(),
    type: core.serialization.string().optional(),
});

export declare namespace PutCompanyIdCategoryRequest {
    interface Raw {
        name?: string | null;
        type?: string | null;
    }
}
