/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class AccelBooksTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, AccelBooksTimeoutError.prototype);
    }
}
