/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "../../../../core";
import * as AccelBooks from "../../../index";
import urlJoin from "url-join";
import * as serializers from "../../../../serialization/index";
import * as errors from "../../../../errors/index";

export declare namespace Chat {
    interface Options {
        environment: core.Supplier<string>;
        fetcher?: core.FetchFunction;
    }

    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
    }
}

export class Chat {
    constructor(protected readonly _options: Chat.Options) {}

    /**
     * Retrieves chats for a company.
     *
     * @param {string} id
     * @param {Chat.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AccelBooks.InternalServerError}
     *
     * @example
     *     await client.chat.getChats("id")
     */
    public async getChats(id: string, requestOptions?: Chat.RequestOptions): Promise<Record<string, unknown>> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(await core.Supplier.get(this._options.environment), `company/${encodeURIComponent(id)}/chat`),
            method: "GET",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "accelbooks",
                "X-Fern-SDK-Version": "0.0.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return serializers.chat.getChats.Response.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 500:
                    throw new AccelBooks.InternalServerError(_response.error.body);
                default:
                    throw new errors.AccelBooksError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AccelBooksError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.AccelBooksTimeoutError();
            case "unknown":
                throw new errors.AccelBooksError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Creates a new chat for a company.
     *
     * @param {string} id
     * @param {Record<string, unknown>} request
     * @param {Chat.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AccelBooks.InternalServerError}
     *
     * @example
     *     await client.chat.createChat("id", {
     *         "key": "value"
     *     })
     */
    public async createChat(
        id: string,
        request: Record<string, unknown>,
        requestOptions?: Chat.RequestOptions
    ): Promise<Record<string, unknown>> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(await core.Supplier.get(this._options.environment), `company/${encodeURIComponent(id)}/chat`),
            method: "POST",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "accelbooks",
                "X-Fern-SDK-Version": "0.0.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.chat.createChat.Request.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return serializers.chat.createChat.Response.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 500:
                    throw new AccelBooks.InternalServerError(_response.error.body);
                default:
                    throw new errors.AccelBooksError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AccelBooksError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.AccelBooksTimeoutError();
            case "unknown":
                throw new errors.AccelBooksError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Retrieves messages for a specific chat.
     *
     * @param {string} id
     * @param {string} chatId - The ID of the chat to retrieve messages for.
     * @param {Chat.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AccelBooks.InternalServerError}
     *
     * @example
     *     await client.chat.getChatMessages("id", "chatId")
     */
    public async getChatMessages(
        id: string,
        chatId: string,
        requestOptions?: Chat.RequestOptions
    ): Promise<Record<string, unknown>> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                await core.Supplier.get(this._options.environment),
                `company/${encodeURIComponent(id)}/chat/${encodeURIComponent(chatId)}`
            ),
            method: "GET",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "accelbooks",
                "X-Fern-SDK-Version": "0.0.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return serializers.chat.getChatMessages.Response.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 500:
                    throw new AccelBooks.InternalServerError(_response.error.body);
                default:
                    throw new errors.AccelBooksError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AccelBooksError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.AccelBooksTimeoutError();
            case "unknown":
                throw new errors.AccelBooksError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Sends a message in a specific chat.
     *
     * @param {string} id
     * @param {string} chatId
     * @param {Record<string, unknown>} request
     * @param {Chat.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AccelBooks.InternalServerError}
     *
     * @example
     *     await client.chat.sendMessage("id", "chatId", {
     *         "key": "value"
     *     })
     */
    public async sendMessage(
        id: string,
        chatId: string,
        request: Record<string, unknown>,
        requestOptions?: Chat.RequestOptions
    ): Promise<Record<string, unknown>> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                await core.Supplier.get(this._options.environment),
                `company/${encodeURIComponent(id)}/chat/${encodeURIComponent(chatId)}`
            ),
            method: "PUT",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "accelbooks",
                "X-Fern-SDK-Version": "0.0.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.chat.sendMessage.Request.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return serializers.chat.sendMessage.Response.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 500:
                    throw new AccelBooks.InternalServerError(_response.error.body);
                default:
                    throw new errors.AccelBooksError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AccelBooksError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.AccelBooksTimeoutError();
            case "unknown":
                throw new errors.AccelBooksError({
                    message: _response.error.errorMessage,
                });
        }
    }
}
