/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface PostCompanyRequest {
    externalId?: string;
    legalName?: string;
    tin?: string;
    usState?: string;
    entityType?: string;
    phoneNumber?: string;
}
